### ISSUE TITLE
能否将显著性标注居中

### ISSUE THREAD

**Issue by cyddgh** [taowenmicro/EasyStat#1]
您好，EasyStat非常好用，可以快速进行数据分析和作图。但在最后成图时，显著性标注（a,b,c）没有居中（没有位于误差bar的中间，见下图），请问是否可以修改一下R包内的代码？否则可能需要后期导出，在其他软件中微调。
![image](https://user-images.githubusercontent.com/10444611/103166490-7f4f6480-485d-11eb-8386-12409c595dbc.png)

**Comment by cyddgh** [comment]
![image](https://user-images.githubusercontent.com/10444611/103166949-f5ee6100-4861-11eb-9d7a-45cfa9d1d2d2.png)
我将图片导出后，发现显著性标注中有一个空格，导致无法居中显示，例如“a ”而不是“a”

**Comment by taowenmicro** [comment]
目前已经解决了

**Comment by cyddgh** [comment]
> 目前已经解决了

谢谢。
